name: feedback_github
description: A Flutter package for getting better feedback. It allows the user to give interactive feedback directly in the app and upload it as an issue to Github
version: 1.0.0
repository: https://github.com/tempo-riz/feedback_github

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  feedback: ^3.0.0
  http: ^1.0.0
  http_parser: ^4.0.0
  github: ^9.24.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
