name: feedback_github
description: A Flutter package that enables users to submit feedback as GitHub issues, storing images in Firebase Storage.
version: 1.2.0
repository: https://github.com/tempo-riz/feedback_github

topics:
  - github-issue
  - firebase-storage
  - feedback
  - issue-tracker

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  feedback: ^3.0.0
  github: ^9.24.0
  firebase_storage: ^12.0.1
  uuid: ^4.4.0
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  mime: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

false_secrets:
  - "/example/demo/android/app/google-services.json"
  - "/example/demo/lib/firebase_options.dart"
