// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtOqTKBEFwVlF7AuyXffQwNUNbK0jpWto',
    appId: '1:210236146978:android:2baaba580c6fed9394117b',
    messagingSenderId: '210236146978',
    projectId: 'dummy-59109',
    storageBucket: 'dummy-59109.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHGyhdXuGJC7_Z_wlfrH6IPTglhcrvocs',
    appId: '1:210236146978:ios:9a60cd1deef8833d94117b',
    messagingSenderId: '210236146978',
    projectId: 'dummy-59109',
    storageBucket: 'dummy-59109.appspot.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzSMKtHKMztzUFNyxMuF6xnF42tVazafE',
    appId: '1:210236146978:web:df947e73b692e76e94117b',
    messagingSenderId: '210236146978',
    projectId: 'dummy-59109',
    authDomain: 'dummy-59109.firebaseapp.com',
    storageBucket: 'dummy-59109.appspot.com',
    measurementId: 'G-1Y0WTQ7HK3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHGyhdXuGJC7_Z_wlfrH6IPTglhcrvocs',
    appId: '1:210236146978:ios:9a60cd1deef8833d94117b',
    messagingSenderId: '210236146978',
    projectId: 'dummy-59109',
    storageBucket: 'dummy-59109.appspot.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzSMKtHKMztzUFNyxMuF6xnF42tVazafE',
    appId: '1:210236146978:web:ac2e5829abb42fa294117b',
    messagingSenderId: '210236146978',
    projectId: 'dummy-59109',
    authDomain: 'dummy-59109.firebaseapp.com',
    storageBucket: 'dummy-59109.appspot.com',
    measurementId: 'G-6TPFL3TX3X',
  );
}
